trainingPipeline:
  imageTag: v0.0.2
  ecrRegistry: 625715126488.dkr.ecr.us-east-1.amazonaws.com/registry
  mlflowTrackingUrl: http://mlflow.mlflow.svc.cluster.local:5000
  s3ArtifactBucket: mlsecops-workflows-artifacts

retrainingPipeline:
  imageTag: v0.0.4
  ecrRegistry: 625715126488.dkr.ecr.us-east-1.amazonaws.com/registry
  mlflowTrackingUrl: http://mlflow.mlflow.svc.cluster.local:5000
  s3ArtifactBucket: mlsecops-workflows-artifacts
  dynamodbTable: silver-table
  s3ProductionBucket: mlsecops-production-data
  maxItems: "1000"
  replayRatio: "0.3"

servingDeployment:
  imageTag: v0.0.2
  ecrRegistry: 625715126488.dkr.ecr.us-east-1.amazonaws.com/registry
  mlflowTrackingUrl: http://mlflow.mlflow.svc.cluster.local:5000
  modelVersion: 4
